"""Plan rendering: text (human), markdown (PRs/files), json (machines)."""

from __future__ import annotations

import json

from .color import RISK_COLORS, paint
from .plan import Plan

TITLES = {
    "major": "## 🔴 Major — read the changelog, upgrade deliberately",
    "minor": "## 🟡 Minor — backwards compatible, apply this week",
    "patch": "## 🟢 Patch — safe fixes, apply today",
    "same": "## ✅ Up to date",
    "unknown": "## ⚪ Unknown — needs a human look",
}


def format_text(plan: Plan, color: bool = False) -> str:
    counts = plan.counts()
    total = len(plan.items)
    adv = plan.advisory_count()
    head = (f"depwake plan: {total} dep(s) — "
            f"{counts['major']} major, {counts['minor']} minor, "
            f"{counts['patch']} patch, {counts['unknown']} unknown")
    if adv:
        head += f", 🔒 {adv} advisor{'y' if adv == 1 else 'ies'}"
    lines = [head]
    for risk in ("major", "minor", "patch", "unknown"):
        for item in plan.grouped()[risk]:
            d = item.dep
            arrow = f"{d.current} -> {item.latest}" if item.latest else f"{d.current} -> ?"
            flag = "" if d.current_source in ("lock", "pin") else f" [{d.current_source}]"
            lock = " 🔒" if item.advisories else ""
            label = paint(risk.upper().ljust(7), RISK_COLORS[risk], color)
            lines.append(f"  {label} {d.ecosystem:4} {d.name} {arrow}{flag}{lock}")
            if item.note:
                lines.append(f"           {item.note}")
    for note in plan.notes:
        lines.append(f"  note: {note}")
    return "\n".join(lines)


def format_markdown(plan: Plan, root: str = ".") -> str:
    counts = plan.counts()
    adv = plan.advisory_count()
    head = (f"{len(plan.items)} dependencies: "
            f"**{counts['major']}** major, **{counts['minor']}** minor, "
            f"**{counts['patch']}** patch, {counts['unknown']} unknown.")
    if adv:
        head += f" 🔒 **{adv}** advisor{'y' if adv == 1 else 'ies'}."
    lines = [f"# Depwake plan — `{root}`", "", head, ""]
    for risk in ("major", "minor", "patch", "unknown", "same"):
        items = plan.grouped()[risk]
        if not items:
            continue
        lines.append(TITLES[risk])
        lines.append("")
        lines.append("| Package | Current | Latest | Notes |")
        lines.append("|---|---|---|---|")
        for item in items:
            d = item.dep
            cur = f"{d.current or '?'} ({d.current_source})"
            latest = f"[{item.latest}]({item.url})" if item.latest and item.url else (item.latest or "?")
            note = item.note.replace("|", "\\|")
            lines.append(f"| {d.name} ({d.ecosystem}) | {cur} | {latest} | {note} |")
        lines.append("")
    lines.append("_Generated by depwake — patch today, minor this week, major deliberately._")
    sec = [i for i in plan.items if i.advisories]
    if sec:
        lines.append("")
        lines.append("## 🔒 Security notes")
        lines.append("")
        for item in sorted(sec, key=lambda i: (i.dep.ecosystem, i.dep.name.lower())):
            d = item.dep
            lines.append(f"### {d.name} ({d.ecosystem} {d.current})")
            lines.append("")
            for a in item.advisories:
                fixed = f"fixed in {a.fixed_in}" if a.fixed_in else "no fix published"
                lines.append(f"- [{a.id}]({a.url}) — {a.severity} — {fixed}")
                if a.summary:
                    lines.append(f"  {a.summary}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def format_json(plan: Plan) -> str:
    return json.dumps(plan.to_dict(), indent=2)
